#!/bin/bash

echo -e "\e[31mSebelum...\e[0m"
free -h
echo 1 > /proc/sys/vm/drop_caches
sleep 1
echo 2 > /proc/sys/vm/drop_caches
sleep 1
echo 3 > /proc/sys/vm/drop_caches && swapoff -a && swapon -a
sleep 1
echo ""
echo -e "\e[32mSelepas...\e[0m"
free -h
echo "Berjaya..!!!Cache ram anda sudah di bersihkan."
