#!/bin/bash

MYIP=$(wget -qO- ipv4.icanhazip.com)

	clear

	echo "--------------- Selamat datang di Server - IP: $MYIP ---------------"
	echo ""
	cname=$( awk -F: '/model name/ {name=$2} END {print name}' /proc/cpuinfo )
	cores=$( awk -F: '/model name/ {core++} END {print core}' /proc/cpuinfo )
	freq=$( awk -F: ' /cpu MHz/ {freq=$2} END {print freq}' /proc/cpuinfo )
	tram=$( free -m | awk 'NR==2 {print $2}' )
	swap=$( free -m | awk 'NR==4 {print $2}' )
	up=$(uptime|awk '{ $1=$2=$(NF-6)=$(NF-5)=$(NF-4)=$(NF-3)=$(NF-2)=$(NF-1)=$NF=""; print }')

	echo -e "\e[032;1mCPU model:\e[0m $cname"
	echo -e "\e[032;1mNumber of cores:\e[0m $cores"
	echo -e "\e[032;1mCPU frequency:\e[0m $freq MHz"
	echo -e "\e[032;1mTotal amount of ram:\e[0m $tram MB"
	echo -e "\e[032;1mTotal amount of swap:\e[0m $swap MB"
	echo -e "\e[032;1mSystem uptime:\e[0m $up"
	echo "------------------------------------------------------------------------------"
	echo "Sila pilih pilihan dibawah ini"
	echo -e "\e[38;5;82m 1\e[0m)\e[38;5;198mBuat Akaun SSH/OpenVPN "
	echo -e "\e[38;5;82m 2\e[0m)\e[38;5;198mGenerate Akaun SSH/OpenVPN "
	echo -e "\e[38;5;82m 3\e[0m)\e[38;5;198mGanti Password Akaun SSH/OpenVPN"
	echo -e "\e[38;5;82m 4\e[0m)\e[38;5;198mTambah Masa Aktif Akaun SSH/OpenVPN"
	echo -e "\e[38;5;82m 5\e[0m)\e[38;5;198mHapus Akaun SSH/OpenVPN"
	echo -e "\e[38;5;82m 6\e[0m)\e[38;5;198mBuat Akaun PPTP VPN "
	echo -e "\e[38;5;82m 7\e[0m)\e[38;5;198mMonitoring Dropbear"
	echo -e "\e[38;5;82m 8\e[0m)\e[38;5;198mCheck Login Dropbear, OpenSSH, PPTP VPN dan OpenVPN "
	echo -e "\e[38;5;82m 9\e[0m)\e[38;5;198mKill Multi Login Manual"
	echo -e "\e[38;5;82m10\e[0m)\e[38;5;198mDaftar Akaun dan Expire Date"
	echo -e "\e[38;5;82m11\e[0m)\e[38;5;198mDaftar Akaun Aktif "
	echo -e "\e[38;5;82m12\e[0m)\e[38;5;198mDaftar Akaun Expired "
	echo -e "\e[38;5;82m13\e[0m)\e[38;5;198mDisable Akaun Expired"
	echo -e "\e[38;5;82m14\e[0m)\e[38;5;198mDelete Akaun Expired "
	echo -e "\e[38;5;82m15\e[0m)\e[38;5;198mBanned Akaun"
	echo -e "\e[38;5;82m16\e[0m)\e[38;5;198mRestart Dropbear"
	echo -e "\e[38;5;82m17\e[0m)\e[38;5;198mMemory Usage"
 	echo -e "\e[38;5;82m18\e[0m)\e[38;5;198mSpeedtest"
	echo -e "\e[38;5;82m19\e[0m)\e[38;5;198mBenchmark"
	echo -e "\e[38;5;82m20\e[0m)\e[38;5;198mReboot Server"
	echo -e "\e[38;5;82mx\e[0m) Exit"
	read -p "Masukkan pilihan [1-20], kemudian tekan ENTER: " option1
	case $option1 in
		1)
		clear
		user-add
		exit
		;;
		2)
		clear
		user-gen
		exit
		;;
		3)
		clear
		user-pass
		exit
		;;
		4)
		clear
		user-renew
		exit
		;;
		5)
		clear
		user-del
		exit
		;;
		6)
		clear
		user-add-pptp
		exit
		;;
		7)
		clear
		read -p "Isikan Port Dropbear yang akan dimonitor: " PORT
		dropmon $PORT
		exit
		;;
		8)
		clear
		user-login
		exit
		;;
		9)
		clear
		read -p "Isikan Maximal Login (1-2): " MULTILOGIN
		user-limit $MULTILOGIN
		exit
		;;
		10)
		clear
		user-list
		exit
		;;
		11)
		clear
		user-active-list
		exit
		;;
		12)
		clear
		user-expire-list
		exit
		;;
		13)
		clear
		disable-user-expire
		exit
		;;
		14)
		clear
		delete-user-expire
		exit
		;;
		15)
		clear
		banned-user
		exit
		;;
		16)
		clear
		service dropbear restart
		exit
		;;
		17)
		clear
		ps-mem
		exit
		;;
		18)
		clear
		test-speed
		exit
		;;
		19)
		clear
		benchmark
		exit
		;;
		20)
		clear
		reboot
		exit
		;;
		x)
		clear
		exit
		;;
	esac
done

cd ~/
rm -f /root/IP
