#!/bin/bash

MYIP=$(wget -qO- ipv4.icanhazip.com)

	clear

	echo "--------------- Selamat datang di Server - IP: $MYIP ---------------"
	echo ""
	cname=$( awk -F: '/model name/ {name=$2} END {print name}' /proc/cpuinfo )
	cores=$( awk -F: '/model name/ {core++} END {print core}' /proc/cpuinfo )
	freq=$( awk -F: ' /cpu MHz/ {freq=$2} END {print freq}' /proc/cpuinfo )
	tram=$( free -m | awk 'NR==2 {print $2}' )
	swap=$( free -m | awk 'NR==4 {print $2}' )
	up=$(uptime|awk '{ $1=$2=$(NF-6)=$(NF-5)=$(NF-4)=$(NF-3)=$(NF-2)=$(NF-1)=$NF=""; print }')

	echo -e "\e[032;1mCPU model:\e[0m $cname"
	echo -e "\e[032;1mNumber of cores:\e[0m $cores"
	echo -e "\e[032;1mCPU frequency:\e[0m $freq MHz"
	echo -e "\e[032;1mTotal amount of ram:\e[0m $tram MB"
	echo -e "\e[032;1mTotal amount of swap:\e[0m $swap MB"
	echo -e "\e[032;1mSystem uptime:\e[0m $up"
	echo -e "\e[38;5;226m≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡"
	echo -e "\e[38;5;196m     MENU UTAMA | MENU SCRIPT BY Fluxo7"
        echo -e "\e[38;5;226m≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡"
	echo -e "\e[38;5;226m 1\e[0m)\e[38;5;48mBuat Account SSH/OpenVPN "
	echo -e "\e[38;5;226m 2\e[0m)\e[38;5;48mGenerate Akaun SSH/OpenVPN "
	echo -e "\e[38;5;226m 3\e[0m)\e[38;5;48mChange User Password SSH/OpenVPN"
	echo -e "\e[38;5;226m 4\e[0m)\e[38;5;48mTambah Account Aktif Akaun SSH/OpenVPN"
	echo -e "\e[38;5;226m 5\e[0m)\e[38;5;48mDelete User ID SSH/OpenVPN"
	echo -e "\e[38;5;226m 6\e[0m)\e[38;5;48mCreate Account PPTP VPN "
	echo -e "\e[38;5;226m 7\e[0m)\e[38;5;48mMonitoring Dropbear"
	echo -e "\e[38;5;226m 8\e[0m)\e[38;5;48mCheck User Login  "
	echo -e "\e[38;5;226m 9\e[0m)\e[38;5;48mKill Account Login Manual"
	echo -e "\e[38;5;226m10\e[0m)\e[38;5;48mCek Account And Expire Date"
	echo -e "\e[38;5;226m11\e[0m)\e[38;5;48mCek Account Aktif "
	echo -e "\e[38;5;226m12\e[0m)\e[38;5;48mCek Account Expired "
	echo -e "\e[38;5;226m13\e[0m)\e[38;5;48mDisable Account Expired"
	echo -e "\e[38;5;226m14\e[0m)\e[38;5;48mDelete Account Expired "
	echo -e "\e[38;5;226m15\e[0m)\e[38;5;48mBanned Account"
	echo -e "\e[38;5;226m16\e[0m)\e[38;5;48mRestart Dropbear"
	echo -e "\e[38;5;226m17\e[0m)\e[38;5;48mMemory Usage"
 	echo -e "\e[38;5;226m18\e[0m)\e[38;5;48mSpeedtest"
	echo -e "\e[38;5;226m19\e[0m)\e[38;5;48mBenchmark"
	echo -e "\e[38;5;226m20\e[0m)\e[38;5;48mReboot Server"
	echo -e "\e[38;5;196mx\e[0m)\e[38;5;196m Exit Telegram:@OrangKuatSabahanTerkini"
        echo -e "\e[38;5;226m≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡"
	read -p "Masukkan pilihan [1-20], kemudian tekan ENTER: " option1
        echo -e "\e[38;5;226m≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡"
	case $option1 in
		1)
		clear
		user-add
		exit
		;;
		2)
		clear
		user-gen
		exit
		;;
		3)
		clear
		user-pass
		exit
		;;
		4)
		clear
		user-renew
		exit
		;;
		5)
		clear
		user-del
		exit
		;;
		6)
		clear
		user-add-pptp
		exit
		;;
		7)
		clear
		read -p "Isikan Port Dropbear yang akan dimonitor: " PORT
		dropmon $PORT
		exit
		;;
		8)
		clear
		user-login
		exit
		;;
		9)
		clear
		read -p "Isikan Maximal Login (1-2): " MULTILOGIN
		user-limit $MULTILOGIN
		exit
		;;
		10)
		clear
		user-list
		exit
		;;
		11)
		clear
		user-active-list
		exit
		;;
		12)
		clear
		user-expire-list
		exit
		;;
		13)
		clear
		disable-user-expire
		exit
		;;
		14)
		clear
		delete-user-expire
		exit
		;;
		15)
		clear
		banned-user
		exit
		;;
		16)
		clear
		service dropbear restart
		exit
		;;
		17)
		clear
		ps-mem
		exit
		;;
		18)
		clear
		test-speed
		exit
		;;
		19)
		clear
		benchmark
		exit
		;;
		20)
		clear
		reboot
		exit
		;;
		x)
		clear
		exit
		;;
	esac
done

cd ~/
rm -f /root/IP
