#!/bin/bash
# Script by Fluxo7
echo -e "\e[38;5;82-------------------------------"
echo "USERNAME        TANGGAL EXPIRED"
echo "-------------------------------"
while read Fluxo7
do
        AKUN="$(echo $fawzya | cut -d: -f1)"
        ID="$(echo $fawzya | grep -v nobody | cut -d: -f3)"
        exp="$(chage -l $AKUN | grep "Account expires" | awk -F": " '{print $2}')"
        if [[ $ID -ge 500 ]]; then
        printf "%-17s %2s\n" "$AKUN" "$exp"
		fi
done < /etc/passwd
JUMLAH="$(awk -F: '$3 >= 500 && $1 != "nobody" {print $1}' /etc/passwd | wc -l)"
echo -e "\e[38;5;82-------------------------------"
echo "Jumlah akun: $JUMLAH user"
echo "-------------------------------"
echo -e "Script by \e[1;33;44m[ Fluxo7 ]\e[0m"
