#!/bin/bash

if [[ $USER != 'root' ]]; then
	echo "Maaf, Anda harus menjalankan ini sebagai root"
	exit
fi

MYIP=$(wget -qO- ipv4.icanhazip.com)

# go to root
cd

# check registered ip


disable-user-expire
clear

echo "---------------------------- DAFTAR AKAUN SSH ACTIVE --------------------------------"

if [[ $vps = "soned" ]]; then
	echo "                     ALL SUPPORTED BY GollumVPN                           "
	echo "             Script by SYAHZ86   "
else
	echo "                     ALL SUPPORTED BY GollumVPN                           "
	echo "             Script by Fluxo7   "
fi

	echo "            DEVELOPED BY Fluxo7      "
echo ""

cat /root/activeuser.txt
echo ""

cd ~/
rm -f /root/IP
