#!/bin/bash


MYIP=$(wget -qO- ipv4.icanhazip.com)



echo "---------------------------- MEMBUAT AKAUN  PPTP VPN ----------------------------"

if [[ $vps = "soned" ]]; then
	echo "                     ALL SUPPORTED BY  Fluxo7                            "
	echo "             Script by  Fluxo7  "
else
	echo "                     ALL SUPPORTED BY GollumVPN                            "
	echo "             Script by SYAHZ86   "
fi

	echo "            DEVELOPED BY SYAHZ86      "
echo ""

read -p "Isikan username baru: " username
read -p "Isikan password akun [$username]: " password

echo "$username pptpd $password *" >> /etc/ppp/chap-secrets

echo ""
echo "-----------------------------------"
echo "Data Login PPTP VPN:"
echo "-----------------------------------"
echo "Host/IP: $MYIP"
echo "Username: $username"
echo "Password: $password"
echo "-----------------------------------"

cd ~/
rm -f /root/IP
