#!/bin/bash
echo    "--------"
echo -e "\e[31mUSERNAME\e[0m"
echo    "--------"
echo "" > /root/infouser.txt
echo "" > /root/expireduser.txt
echo "" > /root/alluser.txt

cat /etc/shadow | cut -d: -f1,8 | sed /:$/d > /tmp/expirelist.txt
totalaccounts=`cat /tmp/expirelist.txt | wc -l`
for((i=1; i<=$totalaccounts; i++ )); do
	tuserval=`head -n $i /tmp/expirelist.txt | tail -n 1`
	username=`echo $tuserval | cut -f1 -d:`
	userexp=`echo $tuserval | cut -f2 -d:`
	userexpireinseconds=$(( $userexp * 86400 ))
	todaystime=`date +%s`
	if [ $userexpireinseconds -lt $todaystime ] ; then
		 echo $username
	fi
done
rm /tmp/expirelist.txt
